FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY . .

# Убираем backend/, оставляем только src/
RUN dotnet restore src/ClanWarTracker.Api/ClanWarTracker.Api.csproj
RUN dotnet publish src/ClanWarTracker.Api/ClanWarTracker.Api.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ClanWarTracker.Api.dll"]