# === ЭТАП 1: Собираем фронтенд ===
FROM node:20-alpine AS frontend-build
WORKDIR /frontend-src

# Запрашиваем переменную у сборщика Docker
ARG VITE_API_URL
# Делаем её доступной для Vite во время npm run build
ENV VITE_API_URL=$VITE_API_URL

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./
RUN npm run build

# === ЭТАП 2: Собираем .NET API ===
# ... дальше всё без изменений ...