FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY . .

# Путь начинается сразу с src/
RUN dotnet restore src/ClanWarTracker.Worker/ClanWarTracker.Worker.csproj
RUN dotnet publish src/ClanWarTracker.Worker/ClanWarTracker.Worker.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ClanWarTracker.Worker.dll"]