// <auto-generated />
using System;
using ClanWarTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClanWarTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624150000_AddPlayerReferrer")]
    partial class AddPlayerReferrer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlanExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanTier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReminderHoursBeforeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClanTag")
                        .IsUnique();

                    b.HasIndex("TelegramChatId")
                        .IsUnique();

                    b.ToTable("Clans");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReferrerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("PlayerTag");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.PlayerWarSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoatAttacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecksUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecksUsedToday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fame")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarSnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTag");

                    b.HasIndex("WarSnapshotId", "PlayerTag")
                        .IsUnique();

                    b.ToTable("PlayerWarSnapshots");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BracketGeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("BestOf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClanInviteLink")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorPlayerTag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatorTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrizeInfo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTelegramUserId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.TournamentMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextMatchSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantAId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantBId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NextMatchId");

                    b.HasIndex("ParticipantAId");

                    b.HasIndex("ParticipantBId");

                    b.HasIndex("TournamentId", "Round", "SlotIndex")
                        .IsUnique();

                    b.HasIndex("WinnerParticipantId");

                    b.ToTable("TournamentMatches");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.TournamentParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinalPlacement")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "PlayerTag")
                        .IsUnique();

                    b.HasIndex("TournamentId", "TelegramUserId")
                        .IsUnique();

                    b.ToTable("TournamentParticipants");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.WarSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDecksUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFame")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClanId", "SeasonId", "SectionIndex", "PeriodIndex")
                        .IsUnique();

                    b.ToTable("WarSnapshots");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.Player", b =>
                {
                    b.HasOne("ClanWarTracker.Domain.Entities.Clan", "Clan")
                        .WithMany("Players")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.PlayerWarSnapshot", b =>
                {
                    b.HasOne("ClanWarTracker.Domain.Entities.WarSnapshot", "Snapshot")
                        .WithMany("Players")
                        .HasForeignKey("WarSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.TournamentMatch", b =>
                {
                    b.HasOne("ClanWarTracker.Domain.Entities.TournamentMatch", "NextMatch")
                        .WithMany()
                        .HasForeignKey("NextMatchId");

                    b.HasOne("ClanWarTracker.Domain.Entities.TournamentParticipant", "ParticipantA")
                        .WithMany()
                        .HasForeignKey("ParticipantAId");

                    b.HasOne("ClanWarTracker.Domain.Entities.TournamentParticipant", "ParticipantB")
                        .WithMany()
                        .HasForeignKey("ParticipantBId");

                    b.HasOne("ClanWarTracker.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClanWarTracker.Domain.Entities.TournamentParticipant", "WinnerParticipant")
                        .WithMany()
                        .HasForeignKey("WinnerParticipantId");

                    b.Navigation("NextMatch");

                    b.Navigation("ParticipantA");

                    b.Navigation("ParticipantB");

                    b.Navigation("Tournament");

                    b.Navigation("WinnerParticipant");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.TournamentParticipant", b =>
                {
                    b.HasOne("ClanWarTracker.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.WarSnapshot", b =>
                {
                    b.HasOne("ClanWarTracker.Domain.Entities.Clan", "Clan")
                        .WithMany()
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.Clan", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.WarSnapshot", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
