// <auto-generated />
using System;
using ClanWarTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClanWarTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlanExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanTier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReminderHoursBeforeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClanTag")
                        .IsUnique();

                    b.HasIndex("TelegramChatId")
                        .IsUnique();

                    b.ToTable("Clans");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("PlayerTag");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.PlayerWarSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoatAttacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecksUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecksUsedToday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fame")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarSnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTag");

                    b.HasIndex("WarSnapshotId", "PlayerTag")
                        .IsUnique();

                    b.ToTable("PlayerWarSnapshots");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.WarSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDecksUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFame")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClanId", "SeasonId", "SectionIndex", "PeriodIndex")
                        .IsUnique();

                    b.ToTable("WarSnapshots");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.Player", b =>
                {
                    b.HasOne("ClanWarTracker.Domain.Entities.Clan", "Clan")
                        .WithMany("Players")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.PlayerWarSnapshot", b =>
                {
                    b.HasOne("ClanWarTracker.Domain.Entities.WarSnapshot", "Snapshot")
                        .WithMany("Players")
                        .HasForeignKey("WarSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.WarSnapshot", b =>
                {
                    b.HasOne("ClanWarTracker.Domain.Entities.Clan", "Clan")
                        .WithMany()
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.Clan", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("ClanWarTracker.Domain.Entities.WarSnapshot", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
